config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    as :user do
      get "signin" => 'devise/sessions#new'
      delete "signout" => 'devise/sessions#destroy'
      get "signup" => 'devise/registrations#new'
    end 

  root 'pages#home'
  get '/' => 'pages#home'
  get 'about' => 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <div class="container">
<nav class="navbar navbar-dark bg-inverse">
      <!-- Navigation Bar -->
      <div class="header">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
            <% if user_signed_in? %>
              <li class="nav-item pull-md-right"><%= link_to "Log Out", signout_path, method: :delete, class: "nav-link" %></li>
            <% else %>
              <li class="nav-item pull-md-right"><%= link_to "Sign Up", signup_path, class: "btn btn-primary" %></li>
              <li class="nav-item pull-md-right"><%= link_to "Sign In", signin_path, class: "nav-link" %></li>
            <% end %> 

          </ul>
        </nav>
        <h3 class="text-muted">One Month Rails</h3>
      </div>
    </nav>  

      <!-- Flash Message -->

      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>


      <!-- Page Content -->
      <%= yield %>
      
      <!-- Footer -->
      <footer>
        <hr>
        <p>© 2022 One Month</p>
      </footer>

    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/home.html.erb
<!-- Jumbotron -->
<% if user_signed_in? %>
        <h1> Welcome Back! </h1>

<% else %>
    <div class="jumbotron jumbotron-home">
    <div class="container">
                <h1>Welcome to my website!</h1>
                <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <%= link_to "Sign up today »", "#", class: "btn btn-success btn-lg" %> 
        <!-- Columns and Rows -->
        <div class="row">
            <div class="col-lg-6">
                <h2>Subheading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
                <h2>Subheading</h2>
                <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
                <h2>Subheading</h2>
                <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
            </div>
            <div class="col-lg-6">
                <h2>Subheading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
                <h2>Subheading</h2>
                <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
                <h2>Subheading</h2>
                <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
            </div>
        </div>
 <% end %>
        </div>
        </div>